import { FormEvent } from "react";
import { FaEnvelope, FaMapMarkerAlt } from "react-icons/fa";

export default function Contact() {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); console.info("Static contact form submitted", new FormData(event.currentTarget)); };
  const inputClass = "mt-1 w-full rounded-xl border border-gray-300 p-3.5 font-normal outline-none transition focus:border-green focus:ring-4 focus:ring-green/10";
  return (
    <section className="mx-auto min-h-screen max-w-6xl py-8"><div className="mb-10 text-center"><h1 className="text-[32px] font-bold text-dull-green sm:text-[40px] md:text-[64px]">Get In Touch</h1><p className="text-muted">We’d love to hear from you. Send us your questions, ideas, or feedback.</p></div><div className="overflow-hidden rounded-[25px] bg-white shadow-card lg:grid lg:grid-cols-[5fr_7fr]"><div className="bg-gradient-to-br from-green to-dull-green p-8 text-white sm:p-12"><h2 className="text-3xl font-bold">Let’s Connect</h2><p className="my-6">Have questions about BE GREEN HEROES? Feel free to contact us anytime.</p><div className="mb-5 flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white/20"><FaEnvelope /></span><span className="break-all">elsamateos@begreenheroes.com</span></div><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white/20"><FaMapMarkerAlt /></span><span>Canada</span></div></div><form onSubmit={submit} className="space-y-5 p-6 sm:p-12"><label className="block font-semibold">Full Name<input name="name" placeholder="Enter your name" className={inputClass} /></label><label className="block font-semibold">Email Address<input type="email" name="email" placeholder="Enter your email" className={inputClass} /></label><label className="block font-semibold">Subject<input name="subject" placeholder="Enter subject" className={inputClass} /></label><label className="block font-semibold">Message<textarea name="message" rows={5} placeholder="Write your message" className={inputClass} /></label><button type="submit" className="w-full rounded-xl bg-gradient-to-br from-green to-dull-green p-3.5 font-semibold text-white transition hover:-translate-y-0.5">Send Message</button></form></div></section>
  );
}

